SET IDENTITY_INSERT [dbo].[Garbage] ON
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('81','4','Chocolate');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('82','4','garden cuttings');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('83','4','garden prunings');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('84','1', 'packing tape ');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('85','4','leaves');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('86','4','weeds');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('87','4','skewers');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('88','4','chopsticks');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('89','4','seafood and bones');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('90','2','knife');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('91','1','curtain');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('92','1','Corks');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('93','1','Air freshener');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('94','1','Beauty products');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('95','2','Carton');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('96','2','books');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('97','1','Cellophane');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('98','1','Clothing'); 
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('99','1','textiles'); 
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('100','1','Coat hangers');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('101','1','Compostable plastic');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('102','1','Contact lenses and cases');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('103','1','Crockery');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('104','1','Cutlery');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('105','2','Envelopes');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('106','1','Foam');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('107','1','Hose');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('108','1','Light globes');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('109','1','Kitty litter or pet poo');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('110','1','Light bulbs');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('111','5','Mercury');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('112','1','sanitary napkin');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('113','1','Mops');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('114','1','Nappies');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('115','2','Pizza boxes ');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('116','5','Poisons');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('117','5','pesticides');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('118','5','herbicides ');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('119','5','Printer cartridges ');
INSERT INTO [dbo].[Garbage] ([GarbageId], [BinId], [GarbageName]) VALUES ('120','1','Razors');
SET IDENTITY_INSERT [dbo].[Garbage] OFF
