SET IDENTITY_INSERT [dbo].[Garbage] ON
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('1','Aerosol cans','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('2','Aluminium foil','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('3','Aluminium trays','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('4','Anti-freeze','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('5','Aluminium cans','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('6','Balloons','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('7','band aids','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('8','Batteries ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('9','Biscuit trays ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('10','Bottles ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('11','Bubble wrap ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('12','Bread bags ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('13','Cameras ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('14','glass cans','3');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('15','Cardboard  ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('16','CDs ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('17','Cassette tapes ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('18','Ceramics ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('19','Cigarette butts ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('20','Chemicals ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('21','Cling wrap  ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('22','Computers and accessories ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('23','plastic cans ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('24','electrical or electronic waste','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('25','Formula tins  ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('26','Juice boxes and containers  ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('27','Iron  ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('28','Motor oil  ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('29','Magazines  ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('30','Nappies  ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('31','Newspapers​  ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('32','glass bottles ','3');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('33','glass jars  ','3');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('34','Metal lids  ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('35','Syringes  ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('36','building materials  ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('37','Fruit and vegetable scraps ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('38','Bread, cereal, pasta and rice ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('40','Dairy leftovers  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('41','tea leaves and coffee grounds  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('42','Serviettes and paper towel   ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('43','Tissues  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('44','Meat scraps, seafood and bones  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('45','Crustacean shells  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('46','Citrus, garlic, onion, chilli   ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('47','Leftovers  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('48','Human and animal hair  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('49','Uncoated toothpicks, skewers and chopsticks','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('50','Grass clippings, leaves and weeds  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('51','Watches','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('52','Waxed cardboard','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('53','Vacuum cleaners ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('54','Vacuum cleaner dust','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('55','VHS / Cassette tapes','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('56','Tea bags','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('57','Tetra Paks','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('58','Tissues','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('59','Toaster','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('60','Toothbrushes ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('61','Smoke detectors (household)','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('62','Soft plastics','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('63','Steel cans','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('64','Radios','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('65','Rat poison','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('66','Remote control','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('67','Reusable shopping bags ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('68','Paper and cardboard','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('69','Plant pots ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('70','Pet food bags ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('71','Plastic bags ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('72','Plastic containers and bottles ','2');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('73','Plastic strapping, packing tape ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('74','Polystyrene ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('75','Potting mix bags ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('76','Power tools ','5');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('77','Prunings ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('78','Pyrex ','1');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('79','Flowers, garden cuttings, garden prunings  ','4');
INSERT INTO [dbo].[Garbage] ([GarbageId], [GarbageName], [BinId]) VALUES ('80','Small branches ','4');
SET IDENTITY_INSERT [dbo].[Garbage] OFF
