// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SortWasteVictoria_WebApp.Data;

#nullable disable

namespace SortWasteVictoria_WebApp.Migrations
{
    [DbContext(typeof(SortWasteVictoria_WebAppContext))]
    [Migration("20230311073103_AzureTest")]
    partial class AzureTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SortWasteVictoria_WebApp.Models.Bin", b =>
                {
                    b.Property<int>("BinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinId"));

                    b.Property<string>("BinColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BinId");

                    b.ToTable("Bin");
                });

            modelBuilder.Entity("SortWasteVictoria_WebApp.Models.Garbage", b =>
                {
                    b.Property<int>("GarbageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarbageId"));

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<string>("GarbageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GarbageId");

                    b.HasIndex("BinId");

                    b.ToTable("Garbage");
                });

            modelBuilder.Entity("SortWasteVictoria_WebApp.Models.Garbage", b =>
                {
                    b.HasOne("SortWasteVictoria_WebApp.Models.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bin");
                });
#pragma warning restore 612, 618
        }
    }
}
